import type { Metadata } from "next";
import localFont from 'next/font/local';
import "@/styles/globals.css";
import Header from "@/components/shared/Header";

const geistFont = localFont({
  src: [
    {
      path: '../../public/fonts/Geist-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    }
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistFont.className}>
        <Header />
        {children}
        {/* Footer */}
      </body>
    </html>
  );
}
